version: '3.0'

# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:
  population_size: 1000

actions:

  generate_project_dag:
    run: python:v2 python analysis/project_dag.py
    outputs:
      moderately_sensitive:
        counts: project.dag.md