---
name: CI

on:
  push:
    branches:
      - main

jobs:
  test-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: opensafely-core/research-action@v2

  tag-new-version:
    needs: [test-integration]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Tag new version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_annotated_tag: true
