---
name: CI

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  test-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: opensafely-core/research-action@v2


